apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wle5267sp-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wle5267sp-java-springboot-gitops